## Write a NumPy program to implement following operation
* to add, subtract, multiply, divide arguments element-wise


In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [3]:
a,b

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [4]:
print("a+b = ",np.add(a,b))
print("a-b = ",np.subtract(a,b))
print("a*b = ",np.multiply(a,b))
print("a/b = ",np.divide(a,b))

a+b =  [ 6  8 10 12]
a-b =  [-4 -4 -4 -4]
a*b =  [ 5 12 21 32]
a/b =  [0.2        0.33333333 0.42857143 0.5       ]


* to round elements of the array to the nearest integer

In [5]:
arr = np.array([10.2,11.6,29.8,23.1,1.4])

In [6]:
print("Original Array:", arr)
print("Rounded Array:", np.round(arr))

Original Array: [10.2 11.6 29.8 23.1  1.4]
Rounded Array: [10. 12. 30. 23.  1.]


* to calculate mean across dimension, in a 2D numpy array

In [7]:
array = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [8]:
print("Array : \n",array)
print("Mean of array : ",np.mean(array))
print("Mean of array along axis=1(rows) : ", np.mean(array, axis=1))
print("Mean of array along axis=0(columns) : ", np.mean(array, axis=0))

Array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean of array :  5.0
Mean of array along axis=1(rows) :  [2. 5. 8.]
Mean of array along axis=0(columns) :  [4. 5. 6.]


* to calculate the difference between neighboring elements, element-wise of a given array

In [9]:
array1 = np.array([1, 10, 11, 23, 29])

In [10]:
print("Original Array:", array1)
print("Difference between neighboring elements:", np.diff(array1))

Original Array: [ 1 10 11 23 29]
Difference between neighboring elements: [ 9  1 12  6]
