## Write a NumPy program to implement following operation
* to convert a list of numeric values into a one-dimensional NumPy array

In [1]:
import numpy as np

In [2]:
lst = [10,11,23,29]

In [3]:
a = np.array(lst)

In [4]:
a

array([10, 11, 23, 29])

In [5]:
print("a : ",a)

a :  [10 11 23 29]


* to create a 3x3 matrix with values ranging from 2 to 10

In [6]:
b = np.arange(2,11)

In [7]:
b

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
b = b.reshape(3,3)

In [9]:
print("b : \n",b)

b : 
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


* to append values at the end of an array

In [10]:
print("array before appending : \n",a)

array before appending : 
 [10 11 23 29]


In [11]:
c = np.append(a, [7, 26])

In [12]:
print("array after appending : \n",c)

array after appending : 
 [10 11 23 29  7 26]


* to create another shape from an array without changing its data(3x2 to 2x3)

In [13]:
d = np.array([[1,2],
             [3,4],
             [5,6]])

In [14]:
print("array before reshape : \n",d)

array before reshape : 
 [[1 2]
 [3 4]
 [5 6]]


In [15]:
d = d.reshape(2,3)

In [16]:
print("array after reshape : \n",d)

array after reshape : 
 [[1 2 3]
 [4 5 6]]
