## Write a NumPy program to implement following operation

* **to find the maximum and minimum value of a given flattened array**

In [1]:
import numpy as np

In [2]:
arr = np.array([[1 ,5 ,8], [3, 7, 9], [2, 4, 6]])
a = arr.flatten()
print("Array before flattening : \n", arr)
print("Array after flattening : \n",a)

Array before flattening : 
 [[1 5 8]
 [3 7 9]
 [2 4 6]]
Array after flattening : 
 [1 5 8 3 7 9 2 4 6]


In [3]:
min = np.min(a)
max = np.max(a)

print("Minimum value in flattened array is : ", min)
print("Maximum value in flattened array is : ", max)

Minimum value in flattened array is :  1
Maximum value in flattened array is :  9


* ### **to compute the mean, standard deviation, and variance of a given array along the second axis**

In [4]:
array = np.array([[55, 10, 28], [15, 20, 54], [70, 90, 82]])

print("Array : \n", array)

mean = np.mean(array, axis = 1)
std = np.std(array, axis = 1)
var = np.var(array, axis = 1)

print("Mean of array : ", mean)
print("Standard Deviation of array : ", std)
print("Variance of array : ", var)

Array : 
 [[55 10 28]
 [15 20 54]
 [70 90 82]]
Mean of array :  [31.         29.66666667 80.66666667]
Standard Deviation of array :  [18.49324201 17.32692189  8.21921867]
Variance of array :  [342.         300.22222222  67.55555556]
