### Write a NumPy program to implement following operation
* to split an array of 14 elements into 3 arrays, each with 2, 4, and 8 elements in the original order

In [1]:
import numpy as np

In [2]:
arr = np.arange(1,15)

In [3]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
arr1, arr2, arr3 = np.split(arr,[2,6])

In [5]:
print("array before splitting : \n", arr, "\n Arrays after splitting :  \n array1 : ", arr1, "\n array2 : ", arr2, "\n array3 : ", arr3)

array before splitting : 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14] 
 Arrays after splitting :  
 array1 :  [1 2] 
 array2 :  [3 4 5 6] 
 array3 :  [ 7  8  9 10 11 12 13 14]


* to stack arrays horizontally (column wise)

In [6]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
b = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [7]:
c = np.hstack([a,b])

In [8]:
print("Arrays before stacking horizontally : \n array1 : \n", a, "\n array2 : \n",b)
print("Array after stacking horizontally : \n",c)

Arrays before stacking horizontally : 
 array1 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
 array2 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array after stacking horizontally : 
 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
